### ISSUE TITLE
有时候视频会加载失败。

### ISSUE THREAD

**Issue by yedong-li** [numberwolf/h265web.js#100]
视频信息：
h265视频裸流
问题描述：
有时候视频会无法加载，好像是浏览器加载js文件的顺序影响。
是否偶发：
是，知识有时候会出现这个问题，刷新几次就好
打开谷歌浏览器f12
如果wasm main 出现在[HMR] Waiting for update signal from WDS...前面，视频就会无法打开，反之就可以正常打开视频。

**Comment by numberwolf** [comment]
最好打印日志看下，看来是VUE的bug
