### ISSUE TITLE
MP4_H265无法播放

### ISSUE THREAD

**Issue by huangjintai** [numberwolf/h265web.js#102]
vue项目，MP4-h265播放失败

场景

问题：vue项目，MP4-h265播放失败
模式：点播

视频URL

https://ks3-cn-beijing.ksyun.com/ksplayer/h265/mp4_resource/jinjie_265.mp4

视频信息

分辨率：1080P
时常：60min
码率：500kb/s
编码：H265
封装格式：MP4

问题描述

1）播放器部署服务器上，访问
2）点击播放，出现黑框框，视频无法播放
3）有报错如下 --> 图片
![111](https://user-images.githubusercontent.com/31314795/147184816-7bdc23fe-d3e0-4ef4-9392-c460a0a858fa.jpg)

![222](https://user-images.githubusercontent.com/31314795/147184826-c8d72194-5e99-466c-82e7-623853562626.jpg)

是否偶发

否

**Comment by numberwolf** [comment]
![image](https://user-images.githubusercontent.com/11828206/147185001-d7f48f7a-693d-404f-849d-1eb6078ba97d.png)

刚do完成之后，执行play是不行的，因为播放器需要一个load的时间在里面。
（同时，浏览器的安全性质，不允许自动播放；除非关闭chrome安全限制）

所以刚do执行之前，请先绑定相关事件回调，之后再执行do函数。
![image](https://user-images.githubusercontent.com/11828206/147185356-bad9f0cc-bd35-4a85-8e4d-50d8c2470d7f.png)

`onReadyShowDone`完成之后，用户可以点击播放。（如果关闭了安全限制，可以自动执行播放）
```
player.onReadyShowDone = () => {
    // console.log("onReadyShowDone");
    // to play 封面图加载完成了
};
```

所以，正确顺序是
* player = window.new265webjs(url, config);
* player.onReadyShowDone = function() {...} // 不仅仅绑定这一个事件，但是onReadyShowDone必须绑定才知道什么时候可以播放
* player.do()
* 在`onReadyShowDone`之后可以 player.play()

**Comment by huangjintai** [comment]
我已经把事件都加上去了，为什么在onReadyShowDone（）里面debugger进不去呢？

**Comment by huangjintai** [comment]
我已经把事件都加上去了，为什么在onReadyShowDone（）里面debugger打印不出来呢？

**Comment by huangjintai** [comment]
我已经把事件都加上去了，为什么在onReadyShowDone（）里面debugger打印不出来呢，这个顺序有什么问题吗？
<img width="881" alt="333" src="https://user-images.githubusercontent.com/31314795/147188523-7be7802c-214f-4109-9bff-504515e57547.png">
？

**Comment by numberwolf** [comment]
> 我已经把事件都加上去了，为什么在onReadyShowDone（）里面debugger打印不出来呢，这个顺序有什么问题吗？ <img alt="333" width="881" src="https://user-images.githubusercontent.com/31314795/147188523-7be7802c-214f-4109-9bff-504515e57547.png"> ？

onRender去掉吧
**_还有一些事件写的不对，所有形参的你都没加上。_**
debugger我不知道是什么问题，看看console.log是否加上了，onloadFinish也看看是否有打印。

**Comment by huangjintai** [comment]
debugger就是断点的意思。按照你说的，删掉了onRender，onLoadFinish没形参应该不影响进入方法吧。   onloadFinish、onReadyShowDone两个console都打印不出来，还是一块黑屏。
<img width="922" alt="444" src="https://user-images.githubusercontent.com/31314795/147203211-88d44c83-1c6f-4669-b819-81c12726cbe2.png">

**Comment by numberwolf** [comment]
看下Network下面  网络请求的文件都有哪

有没有missile的js
有没有missile的wasm

**Comment by numberwolf** [comment]
> onLoadFinish没形参应该不影响进入方法吧

既然能弄好为什么就懒得改这一下呢？

**Comment by huangjintai** [comment]
根据小老虎的提示，问题解决了  vue用这段代码可以播放
get() {
        var url = "https://ks3-cn-beijing.ksyun.com/ksplayer/h265/mp4_resource/jinjie_265.mp4";
        var config = {
          // type: "mp4",
          player: "glplayer",
          width: 600,
          height: 400,
          token: "base64:QXV0aG9yOmNoYW5neWFubG9uZ3xudW1iZXJ3b2xmLEdpdGh1YjpodHRwczovL2dpdGh1Yi5jb20vbnVtYmVyd29sZixFbWFpbDpwb3JzY2hlZ3QyM0Bmb3htYWlsLmNvbSxRUTo1MzEzNjU4NzIsSG9tZVBhZ2U6aHR0cDovL3h2aWRlby52aWRlbyxEaXNjb3JkOm51bWJlcndvbGYjODY5NCx3ZWNoYXI6bnVtYmVyd29sZjExLEJlaWppbmcsV29ya0luOkJhaWR1",
          extInfo: {
            moovStartFlag: true,
            ignoreAudio: 1,

          }
        };

        let player = H265webjsModule.createPlayer(url, config);
        console.log('数据', player)
        player.do()
        // 特殊处理 加载播放器
        setTimeout(() => {
          player._makeMP4Player();
        }, 1000);
        // 媒体文件加载完成开始播放
        player.onLoadFinish = () => {
          player.play()
        };

<img width="934" alt="555" src="https://user-images.githubusercontent.com/31314795/147211111-e556839c-4737-48ad-9bde-fe3bf5cb4198.png">

**Comment by numberwolf** [comment]
https://github.com/numberwolf/h265web.js/issues/91
