### ISSUE TITLE
问题：暂停时点击进度条，loading完成后播放按钮还是播放状态

### ISSUE THREAD

**Issue by blueRoach** [numberwolf/h265web.js#103]
场景
问题：暂停时点击进度条，loading完成后播放按钮还是播放状态
模式：点播

视频URL
http://10.90.141.214:8082/example_normal/

视频信息
分辨率：1080P
时常：1min
码率：默认
编码：H265
封装格式：MP4

问题描述
1）加载完成时，暂停视频
2）点击进度条，播放按钮还是播放状态
3）再点击一次恢复正常

是否偶发
是

**Comment by numberwolf** [comment]
这个是Demo是 作者提供的，但是这个框架主要是内核，所以UI界面自己可以改改
