### ISSUE TITLE
hls 获取切片异常问题

### ISSUE THREAD

**Issue by dzpxlz** [numberwolf/h265web.js#105]
在获取m3u8返回后 拼接访问ts路径会多一层级。 导致访问不到ts切片的正确路径。 
例子:
m3u8返回
/2/ewoJIkFjY2Vzc0tleUlkIjoJInluZHciLAoJIkFjY2Vzc0tleVNlY2VydCI6CSJEdzIwMjBkVyIsCgkiRW5kUG9pbnQiOgkiMTcyLjE2LjEwNS41MDo4MDgyIiwKCSJCdWNrZXQiOgkieXpodGVzdCIsCgkiT2JqZWN0IjoJIjUzMDgwMDAwND

h265web.js(异常)
访问ts切片拼接地址:
http://xxxx:xxx/53080000441328000864//2/ewoJIkFjY2Vzc0tleUlkIjoJInluZHciLAoJIkFjY2Vzc0tleVNlY2VydCI6CSJEdzIwMjBkVyIsCgkiRW5kUG9pbnQiOgkiMTcyLjE2LjEwNS41MDo4MDgyIiwKCSJCdWNrZXQiOgkieXpodGVzdCIsCgkiT2JqZWN0IjoJIjUzMDgwMDAwNDQxMzI4MDAwODY0XzE2NDA5MTMyMTgiCn0=
其他播放器(正常)
http://xxxx:xxx/2/ewoJIkFjY2Vzc0tleUlkIjoJInluZHciLAoJIkFjY2Vzc0tleVNlY2VydCI6CSJEdzIwMjBkVyIsCgkiRW5kUG9pbnQiOgkiMTcyLjE2LjEwNS41MDo4MDgyIiwKCSJCdWNrZXQiOgkieXpodGVzdCIsCgkiT2JqZWN0IjoJIjUzMDgwMDAwNDQxMzI4MDAwODY0XzE2NDA5MTMyMTgiCn0=

**Comment by numberwolf** [comment]
Fixed:
https://github.com/numberwolf/h265web.js/releases/tag/v20220117-1
