### ISSUE TITLE
onLoadFinish 未回调时进行直播切换 会增加一个播放窗口

### ISSUE THREAD

**Issue by 18264482935** [numberwolf/h265web.js#106]
场景
问题：onLoadFinish 未回调时进行直播切换 会增加一个播放窗口
模式：直播

视频信息
分辨率：1080P
时常：
码率：默认
编码：H265
封装格式：M3U8

问题描述
1）点击第一个监控
2）在第一个监控onLoadFinish 未回调时进行监控切换
3）播放画面会增加一个

是否偶发
否

**Comment by numberwolf** [comment]
先自行释放一下dom
