### ISSUE TITLE
解码音频异常

### ISSUE THREAD

**Issue by sunboy1991** [numberwolf/h265web.js#110]
# 主题 （这个地方选一个 问题 或者 需求）

### 场景

问题：播放 FLV 失败 无法解码音频
模式：直播

### 视频 URL

[[测试地址](http://play-aliyun.yingtaorelian.com/yingtaorelian/h265-test-aliyun.flv)]

视频信息
分辨率：1080P
时常：60min
码率：500kb/s
编码：H265
封装格式：flv

### 问题描述

1）播放器部署服务器上，访问
2）点击播放，发现失败
3）有报错如下 --> 无报错

等等

### 

是/否

**Comment by numberwolf** [comment]
![image](https://user-images.githubusercontent.com/11828206/149879028-c464cbe4-c6c1-44ee-ad8b-b387deb5cde8.png)

视频有问题，时长怎么为0

**Comment by sunboy1991** [comment]
推的实时流   又开始推流了
