### ISSUE TITLE
没有视频播放失败函数吗

### ISSUE THREAD

**Issue by zhangyuqi77** [numberwolf/h265web.js#113]
# 主题 （这个地方选一个 问题 或者 需求）

### 场景

问题：播放 HLS 失败
模式：直播

### 视频 URL

[http://host:port/a.m3u8](http://host:port/a.m3u8)

视频信息
分辨率：1080P
时常：60min
码率：500kb/s
编码：H265
封装格式：M3U8

### 问题描述

1）播放器部署服务器上，访问
2）点击播放，发现失败
3）有报错如下 --> 图片

等等

### 是否偶发

是/否

### 补充

上传视频

**Comment by numberwolf** [comment]
是这样子的，播放器播放失败 基本都是视频有问题，视频问题千奇百怪。

传统方式是 播放超时就算失败，这是业务侧逻辑
