### ISSUE TITLE
Discussion: Ts 支持度调查 / Ts support survey

### ISSUE THREAD

**Issue by nonzzz** [numberwolf/h265web.js#120]
# 这是一个对h265web.js的ts支持度的调查。

如果在使用`h265web.js`的过程发现ts支持和文档描述不对应请在这个issue进行反馈。包括对ts 支持的建议也可以在这里列出来。

**Comment by XeryYue** [comment]
# This is a survey of typescript support for h265web.js.

If you find that the typescript support does not correspond to the document description during the process of using h265web.js, please provide feedback in this issue. Suggestions including support for ts can also be listed here.
