### ISSUE TITLE
有播放器播放失败事件吗

### ISSUE THREAD

**Issue by zhangyuqi77** [numberwolf/h265web.js#123]
# 主题 （这个地方选一个 问题 或者 需求）

### 场景

问题：播放 HLS 失败
模式：直播

### 视频 URL

[http://host:port/a.m3u8](http://host:port/a.m3u8)

视频信息
分辨率：1080P
时常：60min
码率：500kb/s
编码：H265
封装格式：M3U8

### 问题描述

1）播放器部署服务器上，访问
2）点击播放，发现失败
3）有报错如下 --> 图片

等等

### 是否偶发

是/否

### 补充

上传视频

**Comment by numberwolf** [comment]
目前 这里有一个网络问题捕获
```js
playerObj.onNetworkError = (error) => {
        alert("player - onNetworkError" + error.toString());
    }; // onNetworkError
```

其它没有了 ，播放器本身很特别，失败很难捕获。大多数是多媒体文件的问题。所以最好自己加个超时检测  ,比如多久没有 onReadyShowDone 回调

**Comment by numberwolf** [comment]
这里之后播放器计划自身加一个失败超时检测
