### ISSUE TITLE
监控视频自动播放

### ISSUE THREAD

**Issue by superpope1216** [numberwolf/h265web.js#127]
视频信息
分辨率：1080P
时常：默认
码率：默认
编码：H265
封装格式：M3U8

### 问题描述

1）extInfo : {
            coreProbePart : 0.4,
            probeSize : 8192,
            ignoreAudio : 0
        }
ignoreAudio 设置为1或者0都无法达到静音效果
实际上是想实现监控视频的自动播放，普通的video在静音模式下是可以自动播放的，这个没知道设置muted属性的地方

### 是否偶发

否

**Comment by numberwolf** [comment]
自动播放受限于浏览器安全限制，必须手动触发。
同时，可以先试一下去除掉音频流看看是否可以，
这里ignoreAudio其实不能解决本质问题
