### ISSUE TITLE
如何调试源码

### ISSUE THREAD

**Issue by FengHaiSheng** [numberwolf/h265web.js#128]
标准加密的M3U8貌似不支持，打算自己调试下源码看看。

这个是M3U8资源：http://demos.live.cg-dev.cn/1080p-normal-key.txt

**Comment by numberwolf** [comment]
h265 还是 h264? 源码自己编译就好了 npm的

**Comment by FengHaiSheng** [comment]
h265；

src目录下 npm run dev 会出现死循环

![20220317143307](https://user-images.githubusercontent.com/14888544/158750687-261b3b45-24f9-4281-89e1-df94a385f0da.jpg)
