### ISSUE TITLE
http-flv格式直播流只显示首帧

### ISSUE THREAD

**Issue by xc724655471** [numberwolf/h265web.js#129]
# 主题 （http-flv格式直播流只显示首帧）

### 场景

问题：http-flv格式直播流只显示首帧
模式：直播

### 视频 URL

[ZLMediaKit搭建局域网视频服务器，故无法外网访问)

视频信息
分辨率：1080P
时常：无限
码率：最大256Kbps
编码：H265
封装格式：http-flv

### 问题描述

1）播放器部署本地，开启http-server，访问index-debug.html
2）点击Install Player按钮，出现首帧画面。 
3）当 [onReadyShowDone] 显示，点击Play/Pause按钮
4）画面无变化，Events log打印playerObj.onLoadCache有时打印playerObj.onLoadCacheFinshed
5）很长时间后偶尔可以播放几秒，但非常卡

### 是否偶发

否

### 补充
系统:ubuntu18.04
浏览器:chrmoe Version 88.0.4324.150 (Official Build) (64-bit)
流媒体服务器为ZLMediaKit，采用test_pusher推流海康摄像机rtsp流为rtmp流，rtmp流可正常播放，浏览器播放取ZLMediaKit分发流http-flv。

**Comment by numberwolf** [comment]
是否可以截取一段flv下来

**Comment by xc724655471** [comment]
> 是否可以截取一段flv下来

**Comment by numberwolf** [comment]
是否已经解决目前？

**Comment by xc724655471** [comment]
> 是否已经解决目前？

尚未解决。群里提供过flv文件，但无法定位到问题。视频流目前无法提供可供外网访问地址，暂时无法调试。
