### ISSUE TITLE
有支持硬件解码的计划吗？

### ISSUE THREAD

**Issue by YardWill** [numberwolf/h265web.js#13]
有支持硬件解码的计划吗？

用electron和nodejs addon来实现硬件解码。

**Comment by numberwolf** [comment]
你好，
这里肯定有计划，但是目前在完善能力，预计10月前出一个大版本；之后考虑此类加速相关Feature

**Comment by numberwolf** [comment]
当前利用gpu进行渲染工作

**Comment by dzcpy** [comment]
Mark
