### ISSUE TITLE
播放H265编码的HLS直播视频时，不流畅

### ISSUE THREAD

**Issue by followfire** [numberwolf/h265web.js#132]
# 播放H265编码的HLS直播视频时，不流畅

### 场景

问题：播放 HLS 很卡，不流畅，很久才能跳到下一秒
模式：直播

### 视频 URL

因为是内网监控视频，暂时无法提供

视频信息
分辨率：1080P
时常：无
码率：500kb/s
编码：H265
封装格式：M3U8

### 问题描述

一播放就很卡，很久才能播放完一秒

### 是否偶发

否

### 补充

上传视频

**Comment by numberwolf** [comment]
把电脑其他程序关一下 节省一下cpu再试一下。 并且确认一下 音频是aac吧
