### ISSUE TITLE
github上拉下的代码打开不能直接播放

### ISSUE THREAD

**Issue by tracycuizihao** [numberwolf/h265web.js#134]
github上拉下的代码打开不能直接播放，已经部署httpsever了，报错Invalid typed array length: undefined

Uncaught RangeError: Invalid typed array length: undefined
    at new Int8Array (<anonymous>)
    at updateGlobalBufferAndViews (missile.js:2)
    at missile.js:2

[image](https://user-images.githubusercontent.com/103730954/163537643-7b8a2f18-b455-4628-a70d-baf212fe617c.png)

**Comment by tracycuizihao** [comment]
打开h265web.js-master\example中的index.html，发现报错Invalid typed array length: undefined

**Comment by tracycuizihao** [comment]
![D994737D-17AC-4278-864F-7587F58D4722](https://user-images.githubusercontent.com/103730954/163538594-62b38082-6308-421d-90f4-941888ddc43d.png)

**Comment by XeryYue** [comment]
you can run the example_vue. Or you can oepn the example by using http server. Form the consola, Normally it will display the author copyright infor. but i can't see them. are you sure you are using a http server to run the example?

**Comment by numberwolf** [comment]
用http形式打开，不要用文件形式打开。
