### ISSUE TITLE
 播放H265编码 HLS 失败

### ISSUE THREAD

**Issue by tracycuizihao** [numberwolf/h265web.js#136]
# 播放H265编码 HLS 失败

### 场景

问题：播放 HLS 失败
模式：直播

### 视频 URL

内网监控视频

视频信息
分辨率：1080P
时常：
码率：1000kb/s
编码：H265
封装格式：M3U8

### 问题描述
播放不了hls视频流，日志打印
VideoMissile TSDmuxer avformat open failed:-1094995529, read_size:430222 err:Invalid data found when processing input

![微信图片_20220415171606](https://user-images.githubusercontent.com/103730954/163552605-bcf70917-de31-4835-87fc-1320f03273e9.png)

### 是否偶发

否

### 补充

上传视频

**Comment by numberwolf** [comment]
音频是什么编码的

**Comment by itzhoujun** [comment]
解决了吗
