### ISSUE TITLE
画面是静止的并且报错

### ISSUE THREAD

**Issue by Chai1107** [numberwolf/h265web.js#142]
# 主题 （这个地方选一个 问题 或者 需求）

### 场景

问题：播放 HLS 失败
模式：直播

### 视频 URL

http://10.0.0.176:8080/live/d169.live.mp4

视频信息
![image](https://user-images.githubusercontent.com/72844645/167104821-99987389-84d6-415b-a1f4-684158de5658.png)

### 问题描述

1）播放器在播放时 画面是静止的 并 一直输出 read pkg vod error: -541478725, -541478725, err eof 的错误
![image](https://user-images.githubusercontent.com/72844645/167104942-a4a4cf5c-a8ff-42cf-8308-8cf86d56dd45.png)

等等

### 是否偶发

是/否

### 补充

上传视频

**Comment by girlbymirror** [comment]
MP4嘛？
看这里排查https://github.com/numberwolf/h265web.js/wiki/%E3%80%90QA%E8%A7%A3%E7%AD%94%E3%80%91%E5%BC%80%E5%A7%8B%E6%92%AD%E6%94%BE%E5%90%8E%E9%81%87%E5%88%B0%E7%9A%84%E9%97%AE%E9%A2%98%E7%B3%BB%E5%88%97#q-mp4%E6%94%BE%E8%BF%9B%E5%8E%BB%E4%BB%A5%E5%90%8E%E4%B8%80%E7%9B%B4%E5%8A%A0%E8%BD%BD%E4%B8%8D%E6%88%90%E5%8A%9F%E6%80%8E%E4%B9%88%E5%8A%9E
