### ISSUE TITLE
播放延时5~8秒

### ISSUE THREAD

**Issue by dragonview** [numberwolf/h265web.js#148]
# 主题 
播放延时5~8秒

### 场景
问题：播放FMP4延时5~8秒，其他播放器1~2秒
模式：直播

### 视频 URL
http://192.168.188.1:9080/live/AAC0054360FNZN.live.mp4

视频信息
分辨率：1080P
时常：60min
码率：500kb/s
编码：H264 + G.711A
封装格式：fMP4

### 问题描述
播放FMP4延时5~8秒，其他播放器1~2秒
        config = {
          //type: 'raw265',
          player: "glplayer",
          width: 960,
          height: 540,
          // accurateSeek : true,
          token : token,
          extInfo : {
            rawFps: 24,
            moovStartFlag : true,
            coreProbePart : 0.1,
            ignoreAudio : 1,
            probeSize : 256,
            autoPlay : true,
          }
        };

### 是否偶发
否

**Comment by girlbymirror** [comment]
目前咱们播放矩阵不支持FMP4, 这个是如何播放的？

FLV和HLS、HTTP TS都可以

**Comment by dragonview** [comment]
ZLM做服务端，可以的，就是有延时

**Comment by dragonview** [comment]
FLV反而播放不出来，因为貌似FLV不支持播放G711A

**Comment by numberwolf** [comment]
目前不支持G711A
