### ISSUE TITLE
example_vue报错

### ISSUE THREAD

**Issue by luowenkai** [numberwolf/h265web.js#150]
F12
![image](https://user-images.githubusercontent.com/35422493/169442518-3ee08b8f-56db-41e9-8bdd-d9b926c784c2.png)
页面是
![image](https://user-images.githubusercontent.com/35422493/169442551-93563447-2b1e-4548-8954-d9aaff35186e.png)

**Comment by girlbymirror** [comment]
[【QA解答】初始化失败系列](https://github.com/numberwolf/h265web.js/wiki/%E3%80%90QA%E8%A7%A3%E7%AD%94%E3%80%91%E5%88%9D%E5%A7%8B%E5%8C%96%E5%A4%B1%E8%B4%A5%E7%B3%BB%E5%88%97)
[Q:报错WebAssembly.Memory(): could not allocate memory 怎么解决](https://github.com/numberwolf/h265web.js/wiki/%E3%80%90QA%E8%A7%A3%E7%AD%94%E3%80%91%E5%88%9D%E5%A7%8B%E5%8C%96%E5%A4%B1%E8%B4%A5%E7%B3%BB%E5%88%97#q%E6%8A%A5%E9%94%99webassemblymemory-could-not-allocate-memory-%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3)
