### ISSUE TITLE
missile.js:644 Uncaught ReferenceError: SharedArrayBuffer is not defined     at missile.js:644:45

### ISSUE THREAD

**Issue by worldflyingct** [numberwolf/h265web.js#152]
# 源码中带的例子都无法播放
missile.js:644 Uncaught ReferenceError: SharedArrayBuffer is not defined
    at missile.js:644:45
### 场景
播放example_normal失败
问题：播放example_normal失败
模式：录播

### 视频 URL

[hevc_test_moov_set_head_16s.mp4](hevc_test_moov_set_head_16s.mp4)

视频信息
分辨率：源码中的那个
时常：源码中的那个
码率：源码中的那个
编码：源码中的那个
封装格式：MP4

### 问题描述

一句话不改就会发生，最新的0518，tags

等等

missile.js:644 Uncaught ReferenceError: SharedArrayBuffer is not defined     at missile.js:644:45
### 是否偶发

否

### 补充

上传视频

**Comment by numberwolf** [comment]
你为什么不看WIKI?

https://github.com/numberwolf/h265web.js/wiki/%E3%80%90QA%E8%A7%A3%E7%AD%94%E3%80%91%E5%88%9D%E5%A7%8B%E5%8C%96%E5%A4%B1%E8%B4%A5%E7%B3%BB%E5%88%97#q%E6%8A%A5%E9%94%99uncaught-referenceerror-sharedarraybuffer-is-not-defined-%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3
