### ISSUE TITLE
无法播放，我将demo里面的代码提取出来放在我的项目(react)里面然后打包部署在nginx中但是视频无法

### ISSUE THREAD

**Issue by 163zfw** [numberwolf/h265web.js#155]
# 融合到react项目里面无法播放

### 场景

问题：无法播放
模式：点播

### 视频 URL
视频地址是我本地的地址

视频信息
分辨率：2560*1440
时常：22s
码率：37722kb/s
编码：H265
封装格式：MP4

### 问题描述

1）播放器部署服务器上，访问
2）初始化似乎是没有成功
3）没有报错信息
4)视频地址不管是http://192.168.0.114:8844/upload/20220601/h265.mp4还是demo里面提供的都无法播放

等等

### 是否偶发

否

### 补充
nginx的配置文件也已经修改，demo放在nginx中可以播放但是在我的项目中不可以播
![image](https://user-images.githubusercontent.com/107388813/173293640-f7e49280-b6d6-4a0d-90a3-74342dbabaac.png)
![image](https://user-images.githubusercontent.com/107388813/173293736-b241a027-eeeb-4a0c-b37f-386326e920fe.png)

**Comment by girlbymirror** [comment]
demo放在nginx可以播放 那么就没问题。
放在你的项目不能播放，那你的项目和demo引入开发有什么区别？  服务器是否一样？

**Comment by 163zfw** [comment]
多谢，可以了发自我的手机-------- 原始邮件 --------发件人： girlbymirror-adminy ***@***.***>日期： 2022年6月17日周五 17:52收件人： "numberwolf/h265web.js" ***@***.***>抄送： 163zfw ***@***.***>, Author ***@***.***>主    题： Re: [numberwolf/h265web.js] 无法播放，我将demo里面的代码提取出来放在我的项目(react)里面然后打包部署在nginx中但是视频无法 (Issue #155)

demo放在nginx可以播放 那么就没问题。

放在你的项目不能播放，那你的项目和demo引入开发有什么区别？  服务器是否一样？
