### ISSUE TITLE
在运行2022-0712版本demo的时候，报错Uncaught RangeError: WebAssembly.Memory(): Property 'initial': value 32768 is above the upper bound 32767     at missile.js:630

### ISSUE THREAD

**Issue by zo11o** [numberwolf/h265web.js#164]
# 在运行2022-0712版本demo的时候，报错Uncaught RangeError: WebAssembly.Memory(): Property 'initial': value 32768 is above the upper bound 32767     at missile.js:630

### 场景

问题：demo 运行失败
模式：资源播放

### 问题描述

1）clone 资源，example_normal 运行服务
2）浏览器报错 Uncaught RangeError: WebAssembly.Memory(): Property 'initial': value 32768 is above the upper bound 32767     at missile.js:630
3）有报错如下 --> 
![image](https://user-images.githubusercontent.com/24289377/179401742-c37b1781-1745-4f12-9110-5fd9bdb966ab.png)

### 是否偶发

必现

### 补充

上传视频

**Comment by girlbymirror** [comment]
什么浏览器，换chrome 87+的版本 最好最新版本。
missile可以换小内存版本先试试，比如 512mb或者254mb版本
