### ISSUE TITLE
播放编码格式H.265的mp4视频，失败报错

### ISSUE THREAD

**Issue by zzzzzzdk** [numberwolf/h265web.js#168]
# 主题 （这个地方选一个 问题 或者 需求）

### 场景

模式：离线视频

视频信息
分辨率：1080P
时常：35：26
编码：H.265
封装格式：MP4

### 问题描述

1）点击播放，发现失败
2）有报错如下 --> 图片
![image](https://user-images.githubusercontent.com/45683622/182748709-83b8eb83-9a67-4aa5-89e8-f8fabb3eaec8.png)
![image](https://user-images.githubusercontent.com/45683622/182748741-34c498db-ed45-416f-90e0-3cf056f3950d.png)

等等

### 是否偶发

否

**Comment by girlbymirror** [comment]
看下WIKI
https://github.com/numberwolf/h265web.js/wiki/%E3%80%90QA%E8%A7%A3%E7%AD%94%E3%80%91%E5%BC%80%E5%A7%8B%E6%92%AD%E6%94%BE%E5%90%8E%E9%81%87%E5%88%B0%E7%9A%84%E9%97%AE%E9%A2%98%E7%B3%BB%E5%88%97
