### ISSUE TITLE
h265+rtsp+ws://xxx.ts播放，播放时间越长延迟越来越高，ZLMedia日志显示线程超载,必须刷新页面重新开关流

### ISSUE THREAD

**Issue by jellygithub** [numberwolf/h265web.js#169]
### 问题描述
大佬大富大贵!问题有点小白,h265+rtsp+ws://xxx.ts播放，播放时间越长延迟越来越高，ZLMedia日志显示线程超载,必须刷新页面重新开关流，延迟才降低

![image](https://user-images.githubusercontent.com/15701130/183396615-ef4c069e-9383-42ef-958e-eda905af741c.png)
![image](https://user-images.githubusercontent.com/15701130/183396632-c9fe59e4-8e43-4f00-9574-455b6f209956.png)
![image](https://user-images.githubusercontent.com/15701130/183396656-eee90f2d-75f9-4dd7-b5bc-b218d44153a6.png)

**Comment by girlbymirror** [comment]
累积延迟；
图中onLoadCache是因为i播放过程中 没有足够的缓冲帧 需要暂停 缓冲。这主要是因为你自己本地电脑开了太多占用cpu、或者web的应用导致解码资源不足。

265是用的软解码。

https://github.com/numberwolf/h265web.js/wiki/%E3%80%90QA%E8%A7%A3%E7%AD%94%E3%80%91%E5%BC%80%E5%A7%8B%E6%92%AD%E6%94%BE%E5%90%8E%E9%81%87%E5%88%B0%E7%9A%84%E9%97%AE%E9%A2%98%E7%B3%BB%E5%88%97#q-%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E6%92%AD%E6%94%BE-hevch265%E7%BC%96%E7%A0%81%E8%A7%86%E9%A2%91-%E5%8D%A1%E9%A1%BF
