### ISSUE TITLE
例ws://localhost/live/test.flv，只播放第一帧

### ISSUE THREAD

**Issue by rwerplus** [numberwolf/h265web.js#172]
# 主题 （这个地方选一个 问题 或者 需求）

### 场景

问题：ws://localhost/live/test.flv只播放首帧
模式：直播

### 视频 URL

[ws://localhost/live/test.flv](ws://localhost/live/test.flv)

视频信息
分辨率：1080P
时常：60min
码率：500kb/s
编码：H265
封装格式：ws-flv
备注：
missile.js:1305     Stream #0:0: Audio: aac, 44100 Hz, stereo, fltp
put_char @ missile.js:1305
missile.js:1305     Stream #0:1: Video: hevc (Main), yuv420p(tv), 1920x1080, 5120 kb/s, 50 fps, 50 tbr, 1k tbn, 50 tbc

### 问题描述

1）播放器部署本地，开启http-server，访问index-debug.html
2）点击Install Player按钮，出现首帧画面。
3）当 [onReadyShowDone] 显示，点击Play/Pause按钮，正常打印onLoadCache
4）画面会一直无变化，控制台打印警告
![image](https://user-images.githubusercontent.com/48611415/184780416-ca909693-5bdf-4364-8503-bf2ecea89494.png)

等等

### 必现

是/否

### 补充

上传视频

**Comment by girlbymirror** [comment]
请检查一下 FLV BOX是否封装正常？
可以试一下 转发时候 重新编码 试试，如果可以播放的话 那就是原始流封装有问题
