### ISSUE TITLE
无法在VUE2显示vedio插件，但在VUE3上正常使用包括播放和快进

### ISSUE THREAD

**Issue by ljx0305** [numberwolf/h265web.js#173]
# 问题

### 场景
通过GB28181协议将NVR上录像流推送到ZLMedia，h265web再通过ZLMedia来获取视频流来实现录像回放和快进功能

问题：使用VUE3可正常播放录像和快进，但因项目需求需要使用VUE2，在VUE2上可正常初始化插件，但无法显示video播放控件，无报错
模式：直播(将NVR上的录像当作直播流方式推流和播放)

### 视频 URL

[http://192.168.1.100:10800/rtp/130110000803010001_61b5714a90f44e31947456a5748f71f4.live.mp4)

视频信息
分辨率：1080P
时常：60min
码率：2Mb/s
编码：H264
封装格式：HTTP-fMP4

### 问题描述

1）在VUE2上可正常初始化插件，但无法显示video播放控件，无报错，监听事件未调用
2）写法方式参照VUE3方式来书写
3）工程文件见限件

### 是否偶发
否

### 补充
无
上传视频
上传工程 demo
[h265web_vue2.x_test.zip](https://github.com/numberwolf/h265web.js/files/9351936/h265web_vue2.x_test.zip)

**Comment by ljx0305** [comment]
在Chrome F12调试的时候无法在div下边生成video的dom组件，具体见下图
![91C859F9-3884-4345-B369-02C261A99A0C](https://user-images.githubusercontent.com/10024018/185026845-f52818c2-ba7b-4d6d-b4e5-2f19594534bd.png)

**Comment by ljx0305** [comment]
chrome上VUE3 正常播放视频情况下其div下边会生成video的dom组件，具体情况见下图
![lQLPJxaZNmuju-nNATDNBPawxCX7UB3keXcC_Bb8gsBuAA_1270_304](https://user-images.githubusercontent.com/10024018/185040577-89e1ff0c-c611-4624-84b4-764cb0ab4bcb.png)

**Comment by leikeren** [comment]
已帮你改好。
1.public下未引入missile.js
2.优化：把相应数据等放入data中进行操
[h265web_vue2.x_test.zip](https://github.com/numberwolf/h265web.js/files/9356621/h265web_vue2.x_test.zip)
作
