### ISSUE TITLE
H265编码格式的视频，如果直接seek到视频的最后两秒左右，会出现卡顿播放不了的情况

### ISSUE THREAD

**Issue by wzl080879** [numberwolf/h265web.js#174]
# 主题 （这个地方选一个 问题 或者 需求）

### 场景
问题：H265编码格式的mp4格式视频，如果直接seek到视频的最后两秒左右，会出现卡顿播放不了的情况，换了好多视频，都会出现直接seek到视频最后几秒卡顿的问题

模式：视频点播 

### 视频 URL
mp4的视频

视频信息
分辨率：1080P
时常：10min
码率：500kb/s
编码：H265
封装格式：M3U8

### 问题描述

1）H265编码视频，直接seek到最后两秒左右出现卡顿播不了的情况，控制台中也没有报错
     上传的视频中，视频总时长的10秒，我seek到8秒或者9秒，就会出现一直卡顿的情况，过了十几分钟我在点播放，视频又开始重新播放了，换了好多视频都是这个问题

https://user-images.githubusercontent.com/64002039/185436343-51001d07-d4c1-40fb-82ef-57adfc09c5d5.mp4

等等

### 是否偶发

否

### 补充

上传视频
https://user-images.githubusercontent.com/64002039/185436343-51001d07-d4c1-40fb-82ef-57adfc09c5d5.mp4

**Comment by numberwolf** [comment]
目前应该已经修复 ，硬解码模式上线，最新chrome可以测试（clone github最新版本sdk）
