### ISSUE TITLE
加载流信息成功后播放出错

### ISSUE THREAD

**Issue by flowller** [numberwolf/h265web.js#175]
# 主题 （这个地方选一个 问题 或者 需求）
加载流信息成功后播放出错

### 场景
前端控制台报错内容：
h265webjs-v20220813.js:168 
 Uncaught DOMException: Failed to execute 'start' on 'AudioBufferSourceNode': cannot call start more than once

### 视频 URL

[[http://host:port/a.m3u8](http://host:port/a.m3u8)](http://live-test.meiyijia.com.cn/testmenjin/test.live.mp4)

视频信息
分辨率：1080P
时常：60min
码率：500kb/s
编码：H265
封装格式：M3U8

### 问题描述

1）播放器部署服务器上，访问
2）点击播放，发现失败
3）有报错如下 --> 图片

等等

### 是否偶发
否

**Comment by girlbymirror** [comment]
fragment mp4的吗？ 目前不支持 Http-fmp4
