### ISSUE TITLE
多线程版本js加载报错

### ISSUE THREAD

**Issue by HuZhiBinM** [numberwolf/h265web.js#177]
chrome调试器报错：

missile-multi-thread.js:644 Uncaught ReferenceError: SharedArrayBuffer is not defined
    at missile-multi-thread.js:644:45
missile-multi-thread.js:644 Uncaught ReferenceError: SharedArrayBuffer is not defined
    at missile-multi-thread.js:644:45

**Comment by girlbymirror** [comment]
https://github.com/numberwolf/h265web.js/wiki/%E3%80%90QA%E8%A7%A3%E7%AD%94%E3%80%91%E5%88%9D%E5%A7%8B%E5%8C%96%E5%A4%B1%E8%B4%A5%E7%B3%BB%E5%88%97#q%E6%8A%A5%E9%94%99uncaught-referenceerror-sharedarraybuffer-is-not-defined-%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3

**Comment by girlbymirror** [comment]
[Q:报错Uncaught ReferenceError: SharedArrayBuffer is not defined 怎么解决](https://github.com/numberwolf/h265web.js/wiki/%E3%80%90QA%E8%A7%A3%E7%AD%94%E3%80%91%E5%88%9D%E5%A7%8B%E5%8C%96%E5%A4%B1%E8%B4%A5%E7%B3%BB%E5%88%97#q%E6%8A%A5%E9%94%99uncaught-referenceerror-sharedarraybuffer-is-not-defined-%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3)
