### ISSUE TITLE
播放 HLS 截图失败，没有报错

### ISSUE THREAD

**Issue by jackxuechen** [numberwolf/h265web.js#180]
# 主题 （这个地方选一个 问题 或者 需求）

### 场景

问题：播放 HLS 截图失败，没有报错
模式：直播

### 视频 URL

http://39.134.115.163:8080/PLTV/88888910/224/3221225642/index.m3u8

视频信息
分辨率：NA
时常：NA
码率：NA
编码：H264
封装格式：M3U8

### 问题描述

1）播放器部署服务器上，访问
2）点击播放，等视频出来，点击snapshot
3）没有截图

**Comment by girlbymirror** [comment]
是否 onReadyShowDone是否调用了？ 这个event响应才可以播放 截图

**Comment by jackxuechen** [comment]
> 
已经正常播放了。播放后截图的。
