### ISSUE TITLE
H265视频出现加速播放，vlc软件播放是正常的

### ISSUE THREAD

**Issue by dxlani** [numberwolf/h265web.js#182]
# 主题 （加速播放现象）

### 场景

问题：播放 h265格式的mp4出现加速播放
模式：视频文件播放

### 视频 URL

https://oss-jhx-maritime.oss-cn-shanghai.aliyuncs.com/2022/08/31/e81edd1fc6bb4790a81fb08c873f3a08.mp4

视频信息
分辨率：1080P
时常：10S
码率：500kb/s
编码：H265
封装格式：MP4

### 问题描述

播放器出现加速播放的现象，必现，我用VLC播放器能正常速度放

### 是否偶发

 否

**Comment by numberwolf** [comment]
可能是 因为 软解码导致的部分 追帧策略触发了。  或者是视频帧率信息你没有写入MP4
