### ISSUE TITLE
h265web.js视频初始化完成后报错

### ISSUE THREAD

**Issue by oym0308** [numberwolf/h265web.js#183]
# 主题 初始化完成后报错

### 场景

问题：播放 HLS 中
模式：点播

### 视频 URL
https://yun-live.oss-cn-shanghai.aliyuncs.com/record/yunlive/record/yunlive/meeting_1070/2020-11-25-09-27-59_2020-11-25-09-35-52.m3u8

视频信息
分辨率：
时常：
码率：
编码：H264
封装格式：M3U8

### 问题描述

1）视频在加载完毕后一直报 Uncaught DOMException: Failed to execute 'end' on 'TimeRanges': The index provided (0) is greater than or equal to the maximum bound (0).错误
![image](https://user-images.githubusercontent.com/20576931/188259181-ad2618fb-0f58-4b1f-b757-8923025e60d7.png)

2）我是使用的引入加载js
![image](https://user-images.githubusercontent.com/20576931/188259172-9b9ff01b-00d8-4213-9abb-3bf015be5c68.png)
![image](https://user-images.githubusercontent.com/20576931/188259213-6f376db5-4815-4b61-bf30-2dfda3429bba.png)

3）只有在手机模式下才会报这个错
![image](https://user-images.githubusercontent.com/20576931/188782158-f031836e-2cb4-46f6-a5e4-7099a04bd2bf.png)
这你从你github下载的demo，用的是example_normal这个案例 打开在pc端是正常
![image](https://user-images.githubusercontent.com/20576931/188781963-cf6b2c03-6f78-43ac-9688-e37a198cbf20.png)

把浏览器切换到手机模式就开始报错
![image](https://user-images.githubusercontent.com/20576931/188782051-76f8b0d5-795e-4f13-85de-2c3c3fc9437f.png)

### 是否偶发

否

### 补充

用你们在demo是没有问题，可以正常播放没问题

https://user-images.githubusercontent.com/20576931/188259357-c159c2ee-8814-4be9-b897-10af18363247.mp4

**Comment by nonzzz** [comment]
首先你得明白什么是服务器根路径。由于控制台被你清空了。单从现在的复现视频来看。无法得出更多的有效信息。network的确认的目前我们是未知的。其次关于uniapp。我对uniapp不是特别了解。我记得是打包APK只会生成对应的APK文件。具体情况得去核对下uniapp的文档。关于静态资源的存放路径。
