### ISSUE TITLE
音视频同步

### ISSUE THREAD

**Issue by YangShuoys** [numberwolf/h265web.js#185]
# 音视频同步

### 场景

问题：该项目是否在js文件里做了音视频同步

### 问题描述

1）该项目是否在js文件里做了音视频同步
2）在哪个部分做的音视频同步处理

**Comment by numberwolf** [comment]
做了音视频同步 都有处理

**Comment by YangShuoys** [comment]
可以麻烦虎哥指出在js的哪个文件做了音视频同步吗？
