### ISSUE TITLE
播放hls 直播流，每秒钟都会卡很久

### ISSUE THREAD

**Issue by zhengjunfei1102** [numberwolf/h265web.js#186]
场景
问题：播放hls 直播流，每秒钟都会卡很久
模式：直播

视频URL
https://hls-dev-iot.xingshicloud.com:442/live/34020000001310000001@42100000462007000110@0000086024.m3u8?label=15&origin=10.10.20.94&originPort=9003&ssrc=0000086024&token=7e32383e66698c569f66bd8fdd9d6116&ts=1662706280595
url地址只是临时的，每次需要重新获取

视频信息
![image](https://user-images.githubusercontent.com/46403225/189291388-ebf3fed5-509b-45a6-bb95-eb1e519291e4.png)
分辨率：2560*1440
码率：16000
编码：H265
封装格式：M3U8

问题描述
播放hls 直播流，每秒钟都会卡很久，去掉log打印还是会卡

是否偶发
否

**Comment by girlbymirror** [comment]
[Q: 为什么我播放 HEVC/H.265编码视频 卡顿?](https://github.com/numberwolf/h265web.js/wiki/%E3%80%90QA%E8%A7%A3%E7%AD%94%E3%80%91%E5%BC%80%E5%A7%8B%E6%92%AD%E6%94%BE%E5%90%8E%E9%81%87%E5%88%B0%E7%9A%84%E9%97%AE%E9%A2%98%E7%B3%BB%E5%88%97#q-%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E6%92%AD%E6%94%BE-hevch265%E7%BC%96%E7%A0%81%E8%A7%86%E9%A2%91-%E5%8D%A1%E9%A1%BF)

**Comment by girlbymirror** [comment]
软解码 是，所以如果设备资源不足 就分辨率 码率 小点

因为浏览器限制，所以用的是软件解码，软件解码条件性能很苛刻

而且你在浏览器播放，显示框框本身可能连720p都不到

所以视频最多 480p  720p就行了
