### ISSUE TITLE
使用你的example_vue的demo跑起来内存占用2G，内存占用很大，即使没有跑视频，全局引入之后，也有2g内存占用。

### ISSUE THREAD

**Issue by bigFace2019** [numberwolf/h265web.js#188]
# 主题 （这个地方选一个 问题 或者 需求）

### 场景

问题：使用你的example_vue的demo跑起来内存占用2G，内存占用很大，即使没有跑视频，全局引入之后，也有2g内存占用。
模式：直播

### 视频 URL

[[http://host:port/a.m3u8](http://host:port/a.m3u8)](https://gcalic.v.myalicdn.com/gc/fhgcdgm_1/index.m3u8?contentid=2820180516001)

视频信息
分辨率：1080P
时常：60min
码率：500kb/s
编码：H265
封装格式：M3U8

### 问题描述

1）播放视频，正常
2）在浏览器上内存检测2164m
3）最近你在example中更新了h265webjs-v20220912文件，但是在html中还是引入require('./h265webjs-v20220828')，引入错误。
4）截图失败。
### 是否偶发

否

**Comment by numberwolf** [comment]
可以使用替换引入 missile-512mb 最多只占用512mb的内存  或者 Missile-256的文件
