### ISSUE TITLE
Video laggy like playing with low fps

### ISSUE THREAD

**Issue by doanba13** [numberwolf/h265web.js#190]
# Problem

### Scene

Problem：Video with HD resolution playback very slow
Model：VOD

### Media URL
I got video sample in [this website](https://test-videos.co.uk/jellyfish/mp4-h265)

Here is [media link](https://test-videos.co.uk/vids/jellyfish/mp4/h265/1080/Jellyfish_1080_10s_20MB.mp4)

### Media Info

Size：1080P
Duration：10s
Codec：H265
Format：MP4

### Problem Desc
I try to implement your player in React with your document, and the video playback look laggy. I also try with demo site, it has same behavior. When I choose the lowest video quality, the playback got better but still slow a bit. I found in issues section an issue about slow playback, but i can't clear understand it so i open this issue, sorry about that. Really appriciate your work and your help!

**Comment by numberwolf** [comment]
Codec is HEVC?

We support hard-decoding with newest chrome now.

You can try it (newest clone)

**Comment by doanba13** [comment]
thanks for your reply, i will try it
