### ISSUE TITLE
为什么GitHub上写支持flv和websocket-flv，npmjs上就不支持呢，使用也不支持

### ISSUE THREAD

**Issue by A-Yang-Git** [numberwolf/h265web.js#193]
为什么GitHub上写支持flv和websocket-flv，npmjs上就不支持呢，使用也不支持

**Comment by nonzzz** [comment]
因为。这个库是基于webassembly的。对于webassembly的分发需要极不友好。因此npm的包就此废弃。所以一切以github的为准。

**Comment by A-Yang-Git** [comment]
嗯嗯，可是以github为准是支持wsflv的，但却播不了😭

**Comment by nonzzz** [comment]
@A-Yang-Git 这你的加群问一下@numberwolf . 他不怎么看issue。

**Comment by numberwolf** [comment]
> 嗯嗯，可是以github为准是支持wsflv的，但却播不了😭

按照ISSUE标准格式提，试下最新版本
