### ISSUE TITLE
播放视频流失败

### ISSUE THREAD

**Issue by Elmer-kun** [numberwolf/h265web.js#199]
问题：播放视频流失败
模式：直播

(http://192.168.1.95:8038/live?port=1935&app=live&stream=00000000000000000005)

### 问题描述

1）播放器部署服务器上，访问
2）点击播放，发现失败
3）有报错如下 --> 图片
![1666928125219](https://user-images.githubusercontent.com/37469850/198496681-3aecbd3d-ac6f-4980-a2bb-7f64b517067f.png)

**Comment by numberwolf** [comment]
> (http://192.168.1.95:8038/live?port=1935&app=live&stream=00000000000000000005)

这个地址有问题，你这个看不出来到底是什么视频

两种解决办法：

1. 视频路径 加文件类型后缀，比如  /live.flv?port=xxxxxxxxxxxxxxxxxxxxx

2. 看README WIKI，播放器启动配置 type参数加播放类型
