### ISSUE TITLE
hls协议的h265视频播放不成功

### ISSUE THREAD

**Issue by yy-168168** [numberwolf/h265web.js#213]
# 主题 （这个地方选一个 问题 或者 需求）

### 场景

问题：播放 HLS协议的H265 失败

### 视频 URL

[http://10.40.62.50:8010/h265/ooso-playlist.m3u8]

视频信息
分辨率：1080P
时常：60min
码率：500kb/s
编码：H265
封装格式：M3U8

### 问题描述

1）播放器部署服务器上，访问
2）点击播放，视频未出来
3）控制台未报错，wasm已加载

等等

### 是否偶发

是/否

### 补充

上传视频

**Comment by numberwolf** [comment]
可以播放，码率比较大 比较卡
