### ISSUE TITLE
通过FFmpeg转成h265的hls格式视频播放报错

### ISSUE THREAD

**Issue by zyellen** [numberwolf/h265web.js#217]
# 主题 （这个地方选一个 问题 或者 需求）

### 场景

问题：通过FFmpeg转成h265的hls格式视频播放报错
模式：直播

### 视频 URL

[http://host:port/a.m3u8](http://110.86.23.46:8081/stream/camera1/index.m3u8]

视频信息
分辨率：1080P
码率：500kb/s
编码：H265
封装格式：M3U8

### 问题描述

1）播放器部署服务器上，访问
2）点击播放，发现失败
3）有报错如下 VideoMissile TSDmuxer avformat open failed:-1, read_size:154 err:Argument list too long --> 

<img width="732" alt="image" src="https://user-images.githubusercontent.com/53364451/209441252-dd6be814-2fb6-42b5-bae9-5923f0006cdb.png">

### 是否偶发

否

**Comment by numberwolf** [comment]
你好，
![image](https://user-images.githubusercontent.com/11828206/209465503-a38c9883-2eab-470a-8a69-683afe31a3b9.png)

发现你的m3u8嵌入了子m3u8

目前hevc下 hls播放还不支持 子m3u8形式播放， 
我试了一下 ，你把子m3u8地址单独拿出来 可以播放成功
http://110.86.23.46:8081/stream/02603f26-824c-4c6d-86fb-74332fe97147/index.m3u8

![62E9F50279AA167862312CAC1D12DDF0](https://user-images.githubusercontent.com/11828206/209465513-06e390a9-7abf-442c-8fe1-cbef8d17e661.jpg)
