### ISSUE TITLE
vue3 + vite,  window.new265webjs is not a function

### ISSUE THREAD

**Issue by Greasen** [numberwolf/h265web.js#235]
# 主题 （这个地方选一个 问题 或者 需求）

### 场景

问题：window.new265webjs is not a function
安装完，直接运行报错，无法运行
模式：直播

### 视频 URL

[http://host:port/a.m3u8](http://host:port/a.m3u8)

视频信息
分辨率：1080P
时常：60min
码率：500kb/s
编码：H265
封装格式：M3U8

### 问题描述

1）播放器部署服务器上，访问
2）点击播放，发现失败
3）有报错如下 --> 图片

等等

### 是否偶发
否
是/否

### 补充

上传视频

**Comment by Greasen** [comment]
example_vue2 安装完，直接运行也是报 window.new265webjs is not a function

**Comment by nonzzz** [comment]
查看index.html.使用vite 的项目都在该index.html下引入了对应的文件clone 完自己拷贝下。
