### ISSUE TITLE
Use many h265web on 1 page and how to change url

### ISSUE THREAD

**Issue by chienbienbac** [numberwolf/h265web.js#37]
Hi friend,
1. How to use many h265web.js on 1 page?
2. How to change url when h265web is running?

**Comment by numberwolf** [comment]
Hi,

> How to use many h265web.js on 1 page?

* This version unsupport open multi players in 1 web application, I have a new version wait to upgrade.

<br>

> How to change url when h265web is running?

* like other players, u can reload the player with new url.

<hr>

If you want to get newest version as quickly as possible , you can use IM tools and talk to me.

Which IM APP do u use, discord/wechat/qq or others?

**Comment by chienbienbac** [comment]
Hi friend, thanks for your support!
Please add my wechat
![z2117388232542_3949c378bdb94053c400d18be026405f](https://user-images.githubusercontent.com/37771008/95570802-a2822900-0a51-11eb-8059-0ce5fed9f5e3.jpg)

**Comment by numberwolf** [comment]
I forget this issue, 
I have fixed bugs with multi h265web play, you can try it
