### ISSUE TITLE
Demo Change

### ISSUE THREAD

**Issue by Agrejus** [numberwolf/h265web.js#49]
Is there any way you can change the demo to allow an external url?  I would like to test your player to ensure it will work with an h265 MP4 video I have.  I tried to get everything running locally, but was unable to do so.

**Comment by numberwolf** [comment]
You can play with an external url by h265web success.

Will be success with this external url:
`https://findermp.video.qq.com/251/20302/stodownload?encfilekey=Cvvj5Ix3eezXKmVNfShJRUicJJMYPEroic00808a7aXgqxLficlB5eFicLcRadFRvLjb5tEsOhvukXSeW3Hh9gt9Ogc06BKaByGrNZht0VI0MYCob2zAV6NF9tnl2MEjq88qxxUVtbf6qibOibJWicURREOyNLiabYG1960ia3ymzrrWiaBf3VUOiaPNbwMGy3UgHzkQQO5&adaptivelytrans=0&bizid=1023&dotrans=937&hy=SH&idx=1&m=dfbe64968ef75c4dcadddaf38fb372dc&token=x5Y29zUxcibA8OUawCN97XjTILgaC1Nrib24vgIRVrSyajowopDZ5MiakoJYPVyibs8v&taskid=2021012781544
`

Example (Modify demo's `index.html`):
code:
```javascript
var token = "base64:QXV0aG9yOmNoYW5neWFubG9uZ3xudW1iZXJ3b2xmLEdpdGh1YjpodHRwczovL2dpdGh1Yi5jb20vbnVtYmVyd29sZixFbWFpbDpwb3JzY2hlZ3QyM0Bmb3htYWlsLmNvbSxRUTo1MzEzNjU4NzIsSG9tZVBhZ2U6aHR0cDovL3h2aWRlby52aWRlbyxEaXNjb3JkOm51bWJlcndvbGYjODY5NCx3ZWNoYXI6bnVtYmVyd29sZjExLEJlaWppbmcsV29ya0luOkJhaWR1";
        var type = "mp4";
        var url = "https://findermp.video.qq.com/251/20302/stodownload?encfilekey=Cvvj5Ix3eezXKmVNfShJRUicJJMYPEroic00808a7aXgqxLficlB5eFicLcRadFRvLjb5tEsOhvukXSeW3Hh9gt9Ogc06BKaByGrNZht0VI0MYCob2zAV6NF9tnl2MEjq88qxxUVtbf6qibOibJWicURREOyNLiabYG1960ia3ymzrrWiaBf3VUOiaPNbwMGy3UgHzkQQO5&adaptivelytrans=0&bizid=1023&dotrans=937&hy=SH&idx=1&m=dfbe64968ef75c4dcadddaf38fb372dc&token=x5Y29zUxcibA8OUawCN97XjTILgaC1Nrib24vgIRVrSyajowopDZ5MiakoJYPVyibs8v&taskid=2021012781544";

        const PLAYER_CORE_TYPE_DEFAULT = 0; // 默认内核 recommand!!!!!!
        const PLAYER_CORE_TYPE_CNATIVE = 1; // 测试内核

        var config = {
            type: type,
            player: "glplayer",
            width: 960,
            height: 540,
            accurateSeek : true,
            token : token,
            extInfo : {
                core : PLAYER_CORE_TYPE_DEFAULT,
                // core : PLAYER_CORE_TYPE_CNATIVE,
                coreProbePart : 0.4,
                moovStartFlag : true,
                readyShow : true,
                ignoreAudio : 0
            }
        };
        makeH265webjs(url, config);
```

For others external urls, if you play failed, maybe ` cross-origin` error.

**Comment by Agrejus** [comment]
I tried the test link and I do not see any video, only audio.  Is that intended?

**Comment by numberwolf** [comment]
here `cover image`

![image](https://user-images.githubusercontent.com/11828206/117750238-a96e5580-b245-11eb-98d5-9f1244c64d18.png)

**Comment by Agrejus** [comment]
I will give that a try, thank you

**Comment by numberwolf** [comment]
> I will give that a try, thank you

If you failed again, you can show me your code and suggest the console log with external url.
