### ISSUE TITLE
played hevc slow?

### ISSUE THREAD

**Issue by tracymcgradyzwc** [numberwolf/h265web.js#51]
I played HEVC, but the playback was very slow. Other computers needed to be faster, but it was still very slow. Could you please tell me how to solve it?

 var type = "raw265";
        var url265raw = "http://172.16.7.114:8080/history/out.hevc";
        var config = {
            type: type,
            player: "glplayer",
            width: 960,
            height: 540,
            accurateSeek : true,
            token : token,
            extInfo : {
                readyShow : true,
                rawFps : 30
            }
        };
        var h265Object = makeH265webjsRaw(url265raw, config);

**Comment by numberwolf** [comment]
Maybe the hevc file too large to parse nalu, I will upgrade it in this or next week.

(you can see the play.js, some demo's code for hevc raw play mode is not best way on js)

**Comment by numberwolf** [comment]
Demo Code:
2Part

first
- fetch hevc raw data
- split to nalu

second
- append nalu frame to player
- play

```javascript
//
 // fetch 265
 // you can use your code to fetch vod stream
 // only need `h265webjs.append265NaluFrame(nalBuf);` to append 265 frame
 //
 let rawParser = new RawParserModule();

 let fetchFinished = false;
 let startFetch = false;
 let networkInterval = window.setInterval(() => {
     if (!startFetch) {
         startFetch = true;
         fetch(url265).then(function(response) {
             let pump = function(reader) {
                 return reader.read().then(function(result) {
                     if (result.done) {
                         // console.log("========== RESULT DONE ===========");
                         fetchFinished = true;
                         window.clearInterval(networkInterval);
                         networkInterval = null;
                         return;
                     }
                     let chunk = result.value;
                     rawParser.appendStreamRet(chunk);
                     return pump(reader);
                 });
             }
             return pump(response.body.getReader());
         })
         .catch(function(error) {
             console.log(error);
         });
     }
 }, 1);

 // fps>=30 play else cache
 let naluParseInterval = window.setInterval(() => {
     if (nalBuf != false) {
         // require
         h265webjs.append265NaluFrame(nalBuf);
     } else if (fetchFinished) {
         window.clearInterval(naluParseInterval);
         naluParseInterval = null;
     }
 }, 1);
```

**Comment by tracymcgradyzwc** [comment]
Thank you. I'll try.

**Comment by numberwolf** [comment]
> Thank you. I'll try.

you can only use `append265NaluFrame`, and use websocket send frame to here
