### ISSUE TITLE
请问，同页面下如何创建多个播发器？

### ISSUE THREAD

**Issue by testwen00** [numberwolf/h265web.js#52]
目前播放h265裸流，只使用decoder.js，yuvplayer
初始化如下：
`var c2 = document.getElementById("canvas");

        var renderContext = setupCanvas(c2, {
            preserveDrawingBuffer: false
        });

        let ptsIdx = 0;
        let token = "base64:QXV0aG9yOmNoYW5neWFubG9uZ3xudW1iZXJ3b2xmLEdpdGh1YjpodHRwczovL2dpdGh1Yi5jb20vbnVtYmVyd29sZixFbWFpbDpwb3JzY2hlZ3QyM0Bmb3htYWlsLmNvbSxRUTo1MzEzNjU4NzIsSG9tZVBhZ2U6aHR0cDovL3h2aWRlby52aWRlbyxEaXNjb3JkOm51bWJlcndvbGYjODY5NCx3ZWNoYXI6bnVtYmVyd29sZjExLEJlaWppbmcsV29ya0luOkJhaWR1";
        let version = '100.1.0';
        let decoderMod = null;
        decoderMod = new MissileDecoderModule(token, version);
        decoderMod.initDecoder();
        decoderMod.initFinish = function () {
            console.log("init Finshed");
            var bind_ret = decoderMod.bindCallback(function (y, u, v, stride_y, stride_u, stride_v, width, height, pts, pix_name) {
                              renderFrame(renderContext, y, u, v, stride_y, height);
            });
            console.log("bind ret ", bind_ret);

        };`

通过websocket传入nalu frame.

在多个canvas情况下，没有成功。

**Comment by numberwolf** [comment]
new多个decoder对象，看是否返回了你不同nalu输入解码出来的yuv数据，如果返回了多个yuv数据，那就是webgl窗口的问题，可以确认webgl窗口初始化是否是多个对象的地址。

**Comment by testwen00** [comment]
问题可能出在new decoder上，浏览器调试信息：
initMissile start up
decoder.js:17 initMissile start OK
decoder.js:17 [v] all ok now
decoder.js:17 /********************************************************* 
decoder.js:17 * 
decoder.js:17 * Author: Numberwolf - ChangYanlong
decoder.js:17 * QQ: 531365872
decoder.js:17 * Discord: numberwolf#8694
decoder.js:17 * E-Mail: porschegt23@foxmail.com
decoder.js:17 * Github: https://github.com/numberwolf/h265web.js
decoder.js:17 * 
decoder.js:17 * 作者: 小老虎(Numberwolf)(常炎隆)
decoder.js:17 * QQ: 531365872
decoder.js:17 * Discord: numberwolf#8694
decoder.js:17 * 邮箱: porschegt23@foxmail.com
decoder.js:17 * 博客: https://www.jianshu.com/u/9c09c1e00fd1
decoder.js:17 * Github: https://github.com/numberwolf/h265web.js
decoder.js:17 * 
decoder.js:17 **********************************************************/
video2?deviceId=2c90e347794996ec017949c9e27f0009&channel=33:297 init Finshed
decoder.js:17 initMissile done
decoder.js:17 /********************************************************* 
decoder.js:17 * 
decoder.js:17 * Author: Numberwolf - ChangYanlong
decoder.js:17 * QQ: 531365872
decoder.js:17 * Discord: numberwolf#8694
decoder.js:17 * E-Mail: porschegt23@foxmail.com
decoder.js:17 * Github: https://github.com/numberwolf/h265web.js
decoder.js:17 * 
decoder.js:17 * 作者: 小老虎(Numberwolf)(常炎隆)
decoder.js:17 * QQ: 531365872
decoder.js:17 * Discord: numberwolf#8694
decoder.js:17 * 邮箱: porschegt23@foxmail.com
decoder.js:17 * 博客: https://www.jianshu.com/u/9c09c1e00fd1
decoder.js:17 * Github: https://github.com/numberwolf/h265web.js
decoder.js:17 * 
decoder.js:17 **********************************************************/
decoder.js:17 /********************************************************* 
decoder.js:17 * 
decoder.js:17 * Author: Numberwolf - ChangYanlong
decoder.js:17 * QQ: 531365872
decoder.js:17 * Discord: numberwolf#8694
decoder.js:17 * E-Mail: porschegt23@foxmail.com
decoder.js:17 * Github: https://github.com/numberwolf/h265web.js
decoder.js:17 * 
decoder.js:17 * 作者: 小老虎(Numberwolf)(常炎隆)
decoder.js:17 * QQ: 531365872
decoder.js:17 * Discord: numberwolf#8694
decoder.js:17 * 邮箱: porschegt23@foxmail.com
decoder.js:17 * 博客: https://www.jianshu.com/u/9c09c1e00fd1
decoder.js:17 * Github: https://github.com/numberwolf/h265web.js
decoder.js:17 * 
decoder.js:17 **********************************************************/
decoder.js:17 VideoMissile init done : codec:0
decoder.js:17  codec 265
bind ret  0

初始化信息只有一份，我new了2次decoder

另外会跳到source里：
  (func $ba (;1020;) (export "ba") (param $var0 i32) (param $var1 i32) (param $var2 i32) (param $var3 i32) (result i32)
    (local $var4 i32)
    local.get $var0
    i32.load offset=80
    local.set $var4
    local.get $var0
    local.get $var1
    local.get $var2
    local.get $var3
    local.get $var4
    i32.const 31
    i32.and
    i32.const 176
    i32.add
    call_indirect 

代码如下：
function test1() {
        var c2 = document.getElementById("canvas1");

        var renderContext = setupCanvas(c2, {
            preserveDrawingBuffer: false
        });

        let ptsIdx = 0;
        let token = "base64:QXV0aG9yOmNoYW5neWFubG9uZ3xudW1iZXJ3b2xmLEdpdGh1YjpodHRwczovL2dpdGh1Yi5jb20vbnVtYmVyd29sZixFbWFpbDpwb3JzY2hlZ3QyM0Bmb3htYWlsLmNvbSxRUTo1MzEzNjU4NzIsSG9tZVBhZ2U6aHR0cDovL3h2aWRlby52aWRlbyxEaXNjb3JkOm51bWJlcndvbGYjODY5NCx3ZWNoYXI6bnVtYmVyd29sZjExLEJlaWppbmcsV29ya0luOkJhaWR1";
        let version = '100.1.0';
        let decoderMod = null;
        decoderMod = new MissileDecoderModule(token, version);
        decoderMod.initDecoder();
        decoderMod.initFinish = function () {
            console.log("init Finshed");
            var bind_ret = decoderMod.bindCallback(function (y, u, v, stride_y, stride_u, stride_v, width, height, pts, pix_name) {
                // console.log("======> One Frame ");
                // console.log("======> ======> width, height, pts", width, height, pts);
                // console.log("======> ======> pix_name", pix_name);
                // console.log("======> ======> Y ", stride_y, y);
                // console.log("======> ======> U ", stride_u, u);
                // console.log("======> ======> V ", stride_v, v);

                // _renderYuv420p["default"].renderFrame(yuv, y, u, v, stride_y, height);

                renderFrame(renderContext, y, u, v, stride_y, height);
            });
            console.log("bind ret ", bind_ret);

        };
       
        let ws = new WebSocket("wss://127.0.0.1:8080/test");
        ws.binaryType = 'arraybuffer';
        ws.onopen = function (evt) {
            // console.log("Connection open ...");
            ws.send('playtest');
        };

        ws.onmessage = function (evt) {
            var unit8Arr = new Uint8Array(evt.data);
            console.log("msg length :" + unit8Arr.length);

            var dataBuf = unit8Arr.slice(4, unit8Arr.length);
            decoderMod.decodeNalu(dataBuf, ptsIdx);
            ptsIdx++;
        };

    }

    function test2() {
        var c2 = document.getElementById("canvas2");

        var renderContext = setupCanvas(c2, {
            preserveDrawingBuffer: false
        });

        let ptsIdx = 0;
        let token = "base64:QXV0aG9yOmNoYW5neWFubG9uZ3xudW1iZXJ3b2xmLEdpdGh1YjpodHRwczovL2dpdGh1Yi5jb20vbnVtYmVyd29sZixFbWFpbDpwb3JzY2hlZ3QyM0Bmb3htYWlsLmNvbSxRUTo1MzEzNjU4NzIsSG9tZVBhZ2U6aHR0cDovL3h2aWRlby52aWRlbyxEaXNjb3JkOm51bWJlcndvbGYjODY5NCx3ZWNoYXI6bnVtYmVyd29sZjExLEJlaWppbmcsV29ya0luOkJhaWR1";
        let version = '100.1.0';
        let decoderMod = null;
        decoderMod = new MissileDecoderModule(token, version);
        decoderMod.initDecoder();
        decoderMod.initFinish = function () {
            console.log("init Finshed");
            var bind_ret = decoderMod.bindCallback(function (y, u, v, stride_y, stride_u, stride_v, width, height, pts, pix_name) {
                // console.log("======> One Frame ");
                // console.log("======> ======> width, height, pts", width, height, pts);
                // console.log("======> ======> pix_name", pix_name);
                // console.log("======> ======> Y ", stride_y, y);
                // console.log("======> ======> U ", stride_u, u);
                // console.log("======> ======> V ", stride_v, v);

                // _renderYuv420p["default"].renderFrame(yuv, y, u, v, stride_y, height);

                renderFrame(renderContext, y, u, v, stride_y, height);
            });
            console.log("bind ret ", bind_ret);

        };

        let ws = new WebSocket("wss://127.0.0.1:8080/test");
        ws.binaryType = 'arraybuffer';
        ws.onopen = function (evt) {
            // console.log("Connection open ...");
            ws.send('playtest');
        };

        ws.onmessage = function (evt) {
            var unit8Arr = new Uint8Array(evt.data);
            console.log("msg length :" + unit8Arr.length);

            var dataBuf = unit8Arr.slice(4, unit8Arr.length);
            decoderMod.decodeNalu(dataBuf, ptsIdx);
            ptsIdx++;
        };
        ws.onclose = function (evt) {
            console.log("ws2 Connection closed.");
        };
    }

**Comment by numberwolf** [comment]
你的问题我刚提交代码修复了，测试完成。
https://github.com/numberwolf/h265web.js-wasm-decoder

你可以更新一下。 我的demo现在就是多窗口的。

**Comment by testwen00** [comment]
可以了，非常感谢，另外wasm里是否加了断点，只要f12打开调试，就会进入的debugger状态
断点处：
 (func $ba (;1020;) (export "ba") (param $var0 i32) (param $var1 i32) (param $var2 i32) (param $var3 i32) (result i32)
    (local $var4 i32)
    local.get $var0
    i32.load offset=80
    local.set $var4
    local.get $var0
    local.get $var1
    local.get $var2
    local.get $var3
    local.get $var4
    i32.const 31
    i32.and
    i32.const 176
    i32.add
    call_indirect (param i32 i32 i32 i32) (result i32)
  )

**Comment by numberwolf** [comment]
wasm应该和这个没关系 可以f12以后关闭掉断点

**Comment by numberwolf** [comment]
有用点个star哈

**Comment by testwen00** [comment]
ok，是我这边原因，非常感谢，对这个调试不熟
star支持
