### ISSUE TITLE
如何停止解码方法?

### ISSUE THREAD

**Issue by testwen00** [numberwolf/h265web.js#53]
decoderMod = new MissileDecoderModule(token, version);

decoderMod .release();
停止方法是否正确？

因为多开画面后关闭，貌似内存没有释放。

**Comment by numberwolf** [comment]
是否把相关dom清空了？ 观察的是heap吗？

**Comment by testwen00** [comment]
sorry，我看到的是任务管理器中的chrome进程，3个画面播放，内存不断上涨，最后chrome调试工具点击不了，关掉页面后内存才能释放。

**Comment by testwen00** [comment]
有没有可能是解码性能造成数据累积？内存增长

**Comment by numberwolf** [comment]
我check下这里，内存上涨也可能是init 265的nalu上涨上来的

**Comment by testwen00** [comment]
通过chrome调试工具，看heap snapshots，内存在不断增长，1个小时大概在30m左右，单画面
但不知道如何查找问题，忘帮助。

**Comment by numberwolf** [comment]
checking， 还在定位 明天给答复

**Comment by numberwolf** [comment]
> 通过chrome调试工具，看heap snapshots，内存在不断增长，1个小时大概在30m左右，单画面
> 但不知道如何查找问题，忘帮助。

已解决，
1）在对应项目解决了内存泄露的方法
2）具体Demo更新了释放的示例

**Comment by testwen00** [comment]
问题解决，非常感谢。

**Comment by numberwolf** [comment]
> 问题解决，非常感谢。

哈哈~
