### ISSUE TITLE
react项目中使用需要安装wasm-loader吗？

### ISSUE THREAD

**Issue by HejieShao** [numberwolf/h265web.js#56]
我在react项目中继承了播放器，但是会有报错，报错信息如下
![image](https://user-images.githubusercontent.com/30206057/123192194-ff851880-d4d4-11eb-827e-77730f543a99.png)

是需要安装wasm-loader配置吗？

**Comment by HejieShao** [comment]
这个我找到原因了，现在就是没有创建出播放器

**Comment by numberwolf** [comment]
> 这个我找到原因了，现在就是没有创建出播放器

这里，你是否将wasm文件 放在了你react项目编译好的js 同级目录了吗？

例如：

dist -|
         | - wasm
         | - dist.js

**Comment by pjh714332048** [comment]
> 这个我找到原因了，现在就是没有创建出播放器

大哥能说说怎么解决的吗 我按照owner的方法放好文件了也还是有
