### ISSUE TITLE
播放器创建为null

### ISSUE THREAD

**Issue by HejieShao** [numberwolf/h265web.js#57]
使用H256webjsModule.createPlayer创建，播放器为null
视频链接：http://bus-media-bj.obs.cn-north-4.myhuaweicloud.com/pub/material/20210602/视频H265HEVC_20210602174529129.mp4

**Comment by numberwolf** [comment]
console控制台有报什么错误了吗？

**Comment by numberwolf** [comment]
还有就是把moov box可以前置一下

**Comment by HejieShao** [comment]
控制台并没有报错，但是用index.html里面的dist-player.js的makeH265webjs是没有问题的

**Comment by numberwolf** [comment]
> 控制台并没有报错，但是用index.html里面的dist-player.js的makeH265webjs是没有问题的

用我的方法 把moov前置一下，我试了一下就可以了

**Comment by HejieShao** [comment]
这个是项目中上传到云端的，然后在线预览的，目前没办法这样做；
我想问下，makeH265webjs和H256webjsModule.createPlayer所执行的逻辑是一样的吗？为什么会有不一样的表现呢

**Comment by numberwolf** [comment]
> 这个是项目中上传到云端的，然后在线预览的，目前没办法这样做；
> 我想问下，makeH265webjs和H256webjsModule.createPlayer所执行的逻辑是一样的吗？为什么会有不一样的表现呢

表现不一样吗？ 你用import还是哪种方式呢？  makeH265webjs没有这个方法呀，这个方法是我给demo写的play.js 建立的。 不是sdk的方法。

你看下我根目录play.js的代码 ，这部分是引入SDK的逻辑。 看看你是不是配错了。

**Comment by numberwolf** [comment]
不知道你怎么配的config现在

**Comment by HejieShao** [comment]
![image](https://user-images.githubusercontent.com/30206057/123595738-d5f52580-d823-11eb-9b34-a2e9f1a3a213.png)

**Comment by numberwolf** [comment]
moovStartFlag设置为false试试

**Comment by HejieShao** [comment]
这两种都试过了，还是不行；onLoadFinish方法也没有回调

**Comment by numberwolf** [comment]
> 这两种都试过了，还是不行；onLoadFinish方法也没有回调

我再看下吧

**Comment by HejieShao** [comment]
我发现问题了，createPlayer没有自动执行do操作，所以播放器没有加载出来，需要额外执行一下do操作
`let player = H265webjsModule.createPlayer(url, config)
  player["do"]()`

**Comment by numberwolf** [comment]
> 我发现问题了，createPlayer没有自动执行do操作，所以播放器没有加载出来，需要额外执行一下do操作
> `let player = H265webjsModule.createPlayer(url, config) player["do"]()`

对~
