### ISSUE TITLE
H265视频有时候不能暂停

### ISSUE THREAD

**Issue by HejieShao** [numberwolf/h265web.js#58]
视频url:http://bus-media-bj.obs.cn-north-4.myhuaweicloud.com/pub/material/20210630/视频H265HEVC320210626164439404_20210630160017484.mp4

多执行几次play和pause，有时候无法暂停，使用isPlaying获取的状态也是flase

**Comment by numberwolf** [comment]
我测下

**Comment by numberwolf** [comment]
你们的具体操作发一下吧，

是不是seek没有等待seek完成就强制自行操作点了播放按钮，或者没有加载完成时候点击

**Comment by HejieShao** [comment]
就是一个播放和暂停按钮一直点击，等视频加载完成，才开始点击的。播放这个视频的时候，画面会有点卡的时候，就很容易出现无法暂停的问题
![image](https://user-images.githubusercontent.com/30206057/124209139-92e4cc00-db1b-11eb-8078-2a09e11a2651.png)

**Comment by HejieShao** [comment]
我这边测试，这个问题在264的mp4文件是不存在的，265的文件会存在

**Comment by numberwolf** [comment]
> 就是一个播放和暂停按钮一直点击，等视频加载完成，才开始点击的。播放这个视频的时候，画面会有点卡的时候，就很容易出现无法暂停的问题
> ![image](https://user-images.githubusercontent.com/30206057/124209139-92e4cc00-db1b-11eb-8078-2a09e11a2651.png)

赞 有这个线索 我按照这个排查一下

**Comment by numberwolf** [comment]
请更新最新版本，目前已修复


# Remind!
因为使用软解码能力（浏览器上无法做硬解码加速 与 汇编优化）,故设备电脑配置性能 会 影响播放器性能！

请注意：

* 视频帧率最好 <= 30fps
    * 建议：24fps

* 视频码率最好 <= 1.5Mb
    * 建议：300~600kbps (HEVC/H.265可提供较高的压缩率)

**Comment by HejieShao** [comment]
好，更新看了确实流畅了很多！然后H265的seek到某个时间点，需要等比较长的时间才会跳到对应的时间点，这个是因为H265需要重新进行解码吗？

**Comment by numberwolf** [comment]
> 好，更新看了确实流畅了很多！然后H265的seek到某个时间点，需要等比较长的时间才会跳到对应的时间点，这个是因为H265需要重新进行解码吗？

对，不解码无法播放，因为是精准seek，而且浏览器能力比较弱 这个已经是优化过的速度。

**Comment by HejieShao** [comment]
好 ，明白了
