### ISSUE TITLE
请问 播放器在谷歌浏览器上正常 但是在360浏览器上会报错怎么解决，load component failed RangeError: Start offset undefined is outside the bounds of the buffer

### ISSUE THREAD

**Issue by hvy2243** [numberwolf/h265web.js#67]

**Comment by numberwolf** [comment]
360浏览器属于非标准浏览器，对wasm无法支持，这个得找厂商解决。此处无法解决。

![image](https://user-images.githubusercontent.com/11828206/125247002-0e692900-e325-11eb-9c95-6680e4f00c71.png)

**Comment by dzcpy** [comment]
同样出了此问题 `Chromium 86.0.4240.198`
![image](https://user-images.githubusercontent.com/203980/137569162-ec80ae4b-ebc5-44b3-aa56-30acc0783a11.png)

**Comment by numberwolf** [comment]
> 同样出了此问题 `Chromium 86.0.4240.198` ![image](https://user-images.githubusercontent.com/203980/137569162-ec80ae4b-ebc5-44b3-aa56-30acc0783a11.png)

升级你的chrome试试 要支持wasm
