### ISSUE TITLE
How to run your demo ?

### ISSUE THREAD

**Issue by pubpy2015** [numberwolf/h265web.js#77]
Hi,

I am running index.html in both folders: example and example_normal but it cannot play anything:
![image](https://user-images.githubusercontent.com/59004953/138297585-0702af9f-e172-4fb6-afa8-1fb901e018e1.png)

**Comment by numberwolf** [comment]
* example:
Open file : index.html,  then modify the url to your h265 media's url

* example_normal:
Open file : example.js then modify the url to your h265 media's url

# Warning:!!!!
Do not open it by file protocol!!!!!!!!!!  Put it in your webserver path(like nginx/apache)
