### ISSUE TITLE
Only local video?

### ISSUE THREAD

**Issue by diaconuliviu85** [numberwolf/h265web.js#78]
Hello good, very good work.

With local video it works, but it doesn't work for me with video on an http server or via ftp.
And the second question, can I use this project on a web page? or is it not allowed?

Thank you.And a very good job.

**Comment by numberwolf** [comment]
Dont use ftp on web, it's not a good way.

H265web support http uri,  so you need to check your cross-origin problem.

> can I use this project on a web page? or is it not allowed?

Yes, you can~ (please give me a star, thx~
