### ISSUE TITLE
Is there any way to play static MPEG-2 ts files ?

### ISSUE THREAD

**Issue by Enoooch** [numberwolf/h265web.js#79]
Got a static MPEG-2 ts file list from server, I don't know if there is a way to play ts file in the browser.

**Comment by numberwolf** [comment]
> Got a static MPEG-2 ts file list from server, I don't know if there is a way to play ts file in the browser.

I think you means m3u8/hls?????  No others type for ts file list.
And player can play single ts file

**Comment by Enoooch** [comment]
Yeah, ts file was cut from hls stream for playback.

**Comment by numberwolf** [comment]
its my pressure~
