### ISSUE TITLE
HTTP FLV

### ISSUE THREAD

**Issue by ouyuan666** [numberwolf/h265web.js#81]
你好！我发现个问题，播放h265的mp4是没有问题的，但是播放http-flv h265视频画面比较卡不清楚什么问题,http-flv 264是没问题的，而且http-flv 265的画面有时候会变灰，难道是我配置有问题？正常的话应该改demo中的地址就行了吧？

**Comment by numberwolf** [comment]
没问题，具体卡不卡，得看你视频属性。同时看你推流是怎么推的，什么流。
