### ISSUE TITLE
Uncaught TypeError: this.player is null

### ISSUE THREAD

**Issue by tankvn** [numberwolf/h265web.js#82]
@numberwolf 

How to play relatively m3u8 URL?

> #EXTM3U
> #EXT-X-VERSION:3
> #EXT-X-STREAM-INF:BANDWIDTH=50174,CODECS="hvc1.1.6.L90.B1.0.1.1",RESOLUTION=704x480
> chunklist.m3u8

https://cdn.intface.vn/live/181106e406d27c948cf9001ca88c7b5f772.stream/playlist.m3u8

Error on console: Uncaught TypeError: this.player is null

Thanks for the help!

**Comment by numberwolf** [comment]
hls inside hls?

I will check it

**Comment by numberwolf** [comment]
![image](https://user-images.githubusercontent.com/11828206/140135420-815fb091-a07d-44d4-9cdc-018ad0a4ba4c.png)
I watched this error, you url can not cross-origin.
