### ISSUE TITLE
mp4播放，无法缓冲播放，必须加载完后才播放

### ISSUE THREAD

**Issue by MonkWang** [numberwolf/h265web.js#83]
mp4播放，无法缓冲播放，必须加载完后才播放

**Comment by numberwolf** [comment]
那是因为你的MP4的MOOV BOX在最后面，你可以IO操作一下，放在最前面。

```
ffmpeg -i input.mp4 \
-vcodec copy \
-acodec copy \
-movflags faststart \
-y output.mp4
```

这样子就可以

**Comment by numberwolf** [comment]
check moov:
```
ffprobe pianwei.mp4 -v trace 2>&1 | grep 'moov\|mdat
```

* mdat before moov
![image](https://user-images.githubusercontent.com/11828206/140485567-91c13201-402f-4987-b562-84783b65e24b.png)

* moov before mdat (right!)
![image](https://user-images.githubusercontent.com/11828206/140485648-1bcb5de8-4abe-4d69-8b06-c689b49589d9.png)
