### ISSUE TITLE
h265格式的mp4播放，出现画屏

### ISSUE THREAD

**Issue by MonkWang** [numberwolf/h265web.js#84]
h265格式的mp4播放，出现画屏
![image](https://user-images.githubusercontent.com/19216146/140452716-ee92f673-1471-41d2-9a55-88282af3804e.png)

**Comment by numberwolf** [comment]
第一帧是不是不是I帧  截取下来的 或者NALU头不对

**Comment by numberwolf** [comment]
然后试一下 https://github.com/numberwolf/h265web.js/issues/83
