### ISSUE TITLE
播放h265文件报错

### ISSUE THREAD

**Issue by sunkingsss** [numberwolf/h265web.js#86]
![image](https://user-images.githubusercontent.com/17444344/140472622-27274f87-9737-465a-97fa-34bd6cdc3bab.png)
`const PLAYER_CORE_TYPE_DEFAULT = 0; // 默认播放器内核
        const PLAYER_CORE_TYPE_CNATIVE = 1; // 实验播放器内核

        const token =
            "base64:QXV0aG9yOmNoYW5neWFubG9uZ3xudW1iZXJ3b2xmLEdpdGh1YjpodHRwczovL2dpdGh1Yi5jb20vbnVtYmVyd29sZixFbWFpbDpwb3JzY2hlZ3QyM0Bmb3htYWlsLmNvbSxRUTo1MzEzNjU4NzIsSG9tZVBhZ2U6aHR0cDovL3h2aWRlby52aWRlbyxEaXNjb3JkOm51bWJlcndvbGYjODY5NCx3ZWNoYXI6bnVtYmVyd29sZjExLEJlaWppbmcsV29ya0luOkJhaWR1";

        var config = {
            player: "glplayer",
            width: 960,
            height: 540,
            type: "raw265",
            token: token,
            extInfo: {
                moovStartFlag: true
            }
        };

        const url = "test13.h265"
        let playerObj = window.new265webjs(url, config);

        // playerObj.play()
        console.log(playerObj);
        playerObj.do()
        console.log(playerObj);
        setTimeout(() => {
            console.log(playerObj.player);
            playerObj.player.play()
        }, 5000)`
[test13.zip](https://github.com/numberwolf/h265web.js/files/7481265/test13.zip)

**Comment by numberwolf** [comment]
请参考README的事件，onLoadFinsh onReadyShowDone 之后play

而且你这么playerObj.player.play()  这么调用做法就是错误的。  为什么要自己去操作里面的player对象，API是让你直接在playerObj操作的。

**Comment by sunkingsss** [comment]
大佬您好，我改成这样之后确实没报错了，但是播放不出来

**Comment by sunkingsss** [comment]
大佬您好，我按您说的改了之后确实没有报错了，但是为什么视频文件播放不出来，一直都是黑屏
`const PLAYER_CORE_TYPE_DEFAULT = 0; // 默认播放器内核
        const PLAYER_CORE_TYPE_CNATIVE = 1; // 实验播放器内核

        const token =
            "base64:QXV0aG9yOmNoYW5neWFubG9uZ3xudW1iZXJ3b2xmLEdpdGh1YjpodHRwczovL2dpdGh1Yi5jb20vbnVtYmVyd29sZixFbWFpbDpwb3JzY2hlZ3QyM0Bmb3htYWlsLmNvbSxRUTo1MzEzNjU4NzIsSG9tZVBhZ2U6aHR0cDovL3h2aWRlby52aWRlbyxEaXNjb3JkOm51bWJlcndvbGYjODY5NCx3ZWNoYXI6bnVtYmVyd29sZjExLEJlaWppbmcsV29ya0luOkJhaWR1";

        var config = {
            player: "glplayer",
            width: 960,
            height: 540,
            type: "raw265",
            token: token,
            extInfo: {
                moovStartFlag: true
            }
        };

        // const url = "test13.h265"
        const url = "hevc_test_moov_set_head_16s.mp4"
        let player = window.new265webjs(url, config);

        player.onLoadFinish = function () {
            console.log("load finish");
            player.play()
        }

        player.onReadyShowDone = function(e) {
            console.log("ready done");
        }

        player.do()`

**Comment by numberwolf** [comment]
onReadyShowDone 后面调用Play()  
还有 浏览器里面不要自行 调用play函数，一定要进行交互式调用，就是必须用户点击才可以。不然浏览器安全限制会不让你播放。

改掉这个没用的坏习惯吧。
