### ISSUE TITLE
技术咨询

### ISSUE THREAD

**Issue by Crayon-kk** [numberwolf/h265web.js#88]
你好，rtsp格式的流支持吗？
![image](https://user-images.githubusercontent.com/33805801/141226175-d87cd37f-b0b7-44b8-a6f4-a4f924943626.png)

**Comment by numberwolf** [comment]
不支持，RTSP RTMP均需要借助flash才能将协议数据引入，但是FLASH已经被抛弃，同时是插件，体验不好，故不支持。
