### ISSUE TITLE
CompileError: WebAssembly.instantiate()

### ISSUE THREAD

**Issue by pjh714332048** [numberwolf/h265web.js#89]
您好

![image](https://user-images.githubusercontent.com/46512059/142177805-85e0d45c-3823-4420-8536-66b131e40ee1.png)

当前我的dist里面文件结构是这样的
引用的也是dist/index

请问还有什么地方有问题吗？

**Comment by pjh714332048** [comment]
上面的问题解决了　但是现在浏览器并没有加载missile-v20211104.wasm这个文件

**Comment by numberwolf** [comment]
是否引入了 missile.js了呢？？？

**Comment by numberwolf** [comment]
加下QQ群问吧 实时的

**Comment by numberwolf** [comment]
QQ群: 925466059
