### ISSUE TITLE
H265webjsModule.createPlayer(null, config); error

### ISSUE THREAD

**Issue by testwen00** [numberwolf/h265web.js#90]
错误提示如下：
h265webjs-v20211120.js:168 Uncaught TypeError: Cannot read properties of null (reading 'search')
    at Object.GetUriProtocol (h265webjs-v20211120.js:168)
    at new e (h265webjs-v20211120.js:168)
    at t.new265webjs (h265webjs-v20211120.js:168)

**Comment by numberwolf** [comment]
Fixed https://github.com/numberwolf/h265web.js/releases/tag/v20211123

**Comment by paperman357** [comment]
Uncaught TypeError: Cannot read properties of null (reading 'search')
    at Object.GetUriFormat (dist-play.js:110)
    at new e (dist-play.js:110)
    at t.new265webjs (dist-play.js:110)
    at Function.createPlayer (dist-play.js:161)
    at global.makeH265webjsRawLIVE (dist-play.js:789)

**Comment by numberwolf** [comment]
什么场景 url是啥 什么模式？

**Comment by numberwolf** [comment]
> Uncaught TypeError: Cannot read properties of null (reading 'search') at Object.GetUriFormat (dist-play.js:110) at new e (dist-play.js:110) at t.new265webjs (dist-play.js:110) at Function.createPlayer (dist-play.js:161) at global.makeH265webjsRawLIVE (dist-play.js:789)

什么场景 url是啥 什么模式？

show me your URI,  and play model and others info

**Comment by paperman357** [comment]
URI: WS
model: makeH265webjsRawLIVE
error: var playerObj = _index["default"].createPlayer(null, config); (dist-play.js:789)

I use your example, and I also put my code in dist-play:938
	var ws=null;
	ws = new WebSocket(url265, "marssun");
	ws.binaryType = "arraybuffer";
	ws.onmessage = function (event) {
	console.log("onmessage",event.data);
		playerObj.append265NaluFrame(event.data);
	};
	ws.onerror = (e) => {
		console.log("onerror",e);
		ws.close();
	};
	ws.onclose = (e) => {
		console.log("onclose",e)
	};

**Comment by paperman357** [comment]
I found a solution.
I forgot to add type:"raw265" in my config.

**Comment by numberwolf** [comment]
> I found a solution. I forgot to add type:"raw265" in my config.

yep
