### ISSUE TITLE
移动端无法全屏

### ISSUE THREAD

**Issue by bigkinds** [numberwolf/h265web.js#94]
场景
问题：移动端播放视频无法全屏
模式：点播

视频URL

-https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8

视频信息
分辨率：1080P
时常：14.48
封装格式：M3U8

问题描述
1）本地播放 、视频自动播放之后、点击全屏失败
3）有报错如下 --> 
h265webjs-v20211123.js:168 Uncaught TypeError: Cannot read properties of undefined (reading 'requestFullscreen')
    at e.value (h265webjs-v20211123.js:168)
    at e.value (h265webjs-v20211123.js:168)
  at HTMLAnchorElement.fullScreenBtn.onclick (videoSurveillance2.vue:320)

补充
视频是在线视频（issuse报错图片上传不了）

**Comment by numberwolf** [comment]
https://github.com/numberwolf/h265web.js/releases/tag/v20211204
