### ISSUE TITLE
github上拉下的代码打开不能直接播放

### ISSUE THREAD

**Issue by YXJFXJ** [numberwolf/h265web.js#95]
**问题：**

从github上拉下的代码打开不能直接播放，在h265web.js-master\example目录下，直接点开index.html，发现报错
![PFC TXI54_R2 }4R4FYMM{I](https://user-images.githubusercontent.com/19875888/144822128-82edf534-50b2-482b-aa34-9f8efe83cdcb.png)

**解决办法：**
本地搭建一个httpserver，可以直接指到index.html来访问，即可正常打开
![image](https://user-images.githubusercontent.com/19875888/144822322-a9ba624c-b9b1-4a3e-92d7-8b24f0f98320.png)

**Comment by numberwolf** [comment]
赞~
