### ISSUE TITLE
多视频窗口播放时，点击全屏按钮失效

### ISSUE THREAD

**Issue by fineqianqian** [numberwolf/h265web.js#96]
**场景**
问题：多视频窗口播放，点击全屏按钮，只有第一个视频窗口的全屏按钮有效，其他点击后均会报错
模式：点播

**视频信息**
窗口1视频使用测试视频
分辨率：1080P
时常：10s
码率：500kb/s
编码：H265
封装格式：MP4

**窗口2视频**
分辨率：1080P
时常：7min48s
码率：500kb/s
编码：H265
封装格式：MP4

**问题描述**
1）播放器部署服务器上，访问
2）两个视频都点击播放
3）第一个视频点击全屏，正常
4）第二个视频点击全屏，报错，报错如下

![image](https://user-images.githubusercontent.com/26055087/144953486-4fdf7792-3577-41ac-892b-87bdb8a61ad7.png)

**Comment by numberwolf** [comment]
好的 我看下这个问题

**Comment by numberwolf** [comment]
你好 目前测试没有发现这个问题，请问是否动了播放器内部的dom结构？

**Comment by numberwolf** [comment]
可以加QQ群 仔细看下问题

**Comment by fineqianqian** [comment]
> 你好 目前测试没有发现这个问题，请问是否动了播放器内部的dom结构？

如果两个视频都是demo里的测试视频。点击全屏播放就没有问题，如果使用别的视频，就会有问题。如果使用多窗播放， 如果实例化多个player

**Comment by fineqianqian** [comment]
> 你好 目前测试没有发现这个问题，请问是否动了播放器内部的dom结构？

如果两个视频都是demo里的测试视频。点击全屏播放就没有问题，如果使用别的视频，就会有问题。如果使用多窗播放， 如何实例化多个player呢

**Comment by numberwolf** [comment]
> > 你好 目前测试没有发现这个问题，请问是否动了播放器内部的dom结构？
> 
> 如果两个视频都是demo里的测试视频。点击全屏播放就没有问题，如果使用别的视频，就会有问题。如果使用多窗播放， 如何实例化多个player呢

视频的MOOV BOX是否前置了呢 https://github.com/numberwolf/h265web.js/issues/83

**Comment by numberwolf** [comment]
[replace-files.zip](https://github.com/numberwolf/h265web.js/files/7675108/replace-files.zip)

这三文件
