### ISSUE TITLE
ws流码率问题

### ISSUE THREAD

**Issue by yedong-li** [numberwolf/h265web.js#99]
ws推流最高支持的码率是多少呢？能否支持到2M？

**Comment by numberwolf** [comment]
websocket和播放器没关系，理论上无上限。

但是解码为软解码，和硬件设备，软件资源分配都有关系。 2mb/s 这种 在web上解码 一般的电脑都不太显示，最好1m以下。

265的压缩率是264的两倍，最好先了解以下 编码原理。不要把264的思维套265上，不然也没必要用265了。
